### ISSUE TITLE
How about powershell

### ISSUE THREAD

**Issue by quangkieu** [ntdevlabs/tiny11builder#10]
I think if moving to powershell, you could do a search for prefix app name and remove them so that would work with any win version
And if we use array of prefix, it could do a loop through and remove them

**Comment by jasonpatrickellykrause** [comment]
Agree. 

Not a quick answer, but long-term PowerShell will have more flexibility.

**Comment by rhinotastic** [comment]
can do that with batch scripting too pretty easily. for loop against an app index file.

**Comment by panreyes** [comment]
I understand the commodity of using bat files, as I am also used to them and because they are simpler, they are easy to read.

Still, in bat files we could use some basic functions to at least make the bat file more readable.
I'm working on it in my fork, I will share it soon.

**Comment by innovatodev** [comment]
powershell can be ok level of readability, you can even use powershell from bat files, a lot of bat projects use c# types/powershell code embbed in their bat codes ^^

an example for appx in powershell with a good 'long time support' :

```
$BLACKLIST = @'
YourPhone
Microsoft.OneDrive
Microsoft.Xbox
'@

$SPLIT = $BLACKLIST -split "`n"
$PATTERN = ($SPLIT | ForEach-Object { [Regex]::Escape($_) }) -join '|'
Get-AppxPackage | Select-Object Name, PackageFullName |
Where-Object { $_.PackageFullName -match $PATTERN } |
ForEach-Object {
    # here i can do anything i want with the matched appx
    Write-Host $_.PackageFullName
}
```

This will catch : 
Microsoft.XboxGameCallableUI_1000.22621.1.0_neutral_neutral_cw5n1h2txyewy
Microsoft.XboxGameOverlay_1.54.4001.0_x64__8wekyb3d8bbwe
Microsoft.XboxSpeechToTextOverlay_1.21.13002.0_x64__8wekyb3d8bbwe
Microsoft.XboxIdentityProvider_12.95.3001.0_x64__8wekyb3d8bbwe
Microsoft.XboxGamingOverlay_5.823.1271.0_x64__8wekyb3d8bbwe
Microsoft.OneDriveSync_23033.212.1.0_neutral__8wekyb3d8bbwe
Microsoft.YourPhone_0.23012.167.0_x64__8wekyb3d8bbwe

Since it uses regex you can play with it, add more restricted searchs or more generic ones, line by line ^^

Can adapt this for everything (appxpackages, services start state, scheduled tasks even if you want)

btw it is just an example, but it would allow you do stop doing build specific scripts, and offer to your user a more generic approach ^^

**Comment by panreyes** [comment]
That would be ideal :)

In any case, here's another solution that does not require Powershell scripting:
https://github.com/ntdevlabs/tiny11builder/pull/14/files#diff-251038c5e6cc6da639f0f2025d3ecdf6517fc0d8ac4901754bc1883ba2e0a796R208
```
powershell "Get-AppxProvisionedPackage -Path %TINY11SCRATCHDIR% | Select PackageName" > %TINY11DIR%\tmp\provisioned_packages_in_image.txt

for /f %%p in ('type remove_provisioned_packages.txt') do (
	for /f %%i in ('findstr %%p %TINY11DIR%\tmp\provisioned_packages_in_image.txt') do (
		call :remove_provisioned_package %%p %%i
	)
)
del /f %TINY11DIR%\tmp\provisioned_packages_in_image.txt
```

**Comment by innovatodev** [comment]
The idea about using powershell is because everything in powershell is an object, you are actually calling powershell from batch to export list of objects to disk in order to process them the batch way when you could do this project entirely in a single ps1 script without touching to disk, without invoking another process/scripting tool, powershell has access to c# types, it allow you to remove all dependencies ^^
you can even do a bootable iso without the need of oscdimg in ~15 lines of c# invoked from powershell.

It is really not a bad idea to learn powershell, it will replace batch for everything, and you can still use batch commands without problems into it ^^

```
function New-ISO {
    Param(
        [parameter(Mandatory = $true)][ValidateScript({ Test-Path $_ }) ] $Source,
        [parameter(Mandatory = $true)][ValidateScript({ $_ -like "*.iso" })]$Destination,
        [ValidateSet('CDROM', 'CDR', 'CDRW', 'DVDROM', 'DVDRAM', 'DVDPLUSR', 'DVDPLUSRW', 'DVDPLUSR_DUALLAYER', 'DVDDASHR', 'DVDDASHRW', 'DVDDASHR_DUALLAYER', 'DISK', 'DVDPLUSRW_DUALLAYER', 'HDDVDROM', 'HDDVDR', 'HDDVDRAM', 'BDROM')][string] $MediaType = 'DVDPLUSRW_DUALLAYER'
    )
    Write-Host "Creation new ISO from $Source to $Destination" -ForegroundColor DarkMagenta

    #region C#
    Add-Type -CompilerOptions '/unsafe' -TypeDefinition @'
public class ISOFile
{
  public unsafe static void Create(string Destination, object Stream, int BlockSize, int TotalBlocks)
  {
    int bytes = 0;
    byte[] buf = new byte[BlockSize];
    var ptr = (System.IntPtr)(&bytes);
    var o = System.IO.File.OpenWrite(Destination);
    var i = Stream as System.Runtime.InteropServices.ComTypes.IStream;

    if (o != null) {
      while (TotalBlocks-- > 0) {
        i.Read(buf, BlockSize, ptr); o.Write(buf, 0, bytes);
      }
      o.Flush(); o.Close();
    }
  }
}
'@
    #endregion

    $BootFile = "$Source\efi\microsoft\boot\efisys_noprompt.bin"
    try {
        $Stream = New-Object -ComObject ADODB.Stream -Property @{Type = 1 }
        $Stream.Open()
        $Stream.LoadFromFile((Get-Item -LiteralPath $BootFile).Fullname)
        $Boot = New-Object -ComObject IMAPI2FS.BootOptions
        $Boot.AssignBootImage($Stream)
        $MediaTypeType = @('CDROM', 'CDR', 'CDRW', 'DVDROM', 'DVDRAM', 'DVDPLUSR', 'DVDPLUSRW', 'DVDPLUSR_DUALLAYER', 'DVDDASHR', 'DVDDASHRW', 'DVDDASHR_DUALLAYER', 'DISK', 'DVDPLUSRW_DUALLAYER', 'HDDVDROM', 'HDDVDR', 'HDDVDRAM', 'BDROM')
        $Image = New-Object -com IMAPI2FS.MsftFileSystemImage -Property @{VolumeName = "tiny11" }
        $Image.ChooseImageDefaultsForMediaType($MediaTypeType.IndexOf($MediaType))

        # Creating the ISO file
        $Target = New-Item -Path $Destination -ItemType File -Force:$true -Confirm:$false

        # Adding content to the image
        foreach ($item in (Get-ChildItem $Source)) { $Image.Root.AddTree($item.FullName, $true) }
        if ($Boot) { $Image.BootImageOptions = $Boot }
        $Result = $Image.CreateResultImage()

        # Filling the ISO
        [ISOFile]::Create($Target.FullName, $Result.ImageStream, $Result.BlockSize, $Result.TotalBlocks)
    } catch { Write-Error $_ }
    $ISO = Get-Item $Destination | Select-Object -Property FullName, Length
    Write-Host ("{0} = {1} GB" -f $ISO.FullName, [math]::Round(($ISO.Length / 1024 / 1024 / 1024), 2)) -ForegroundColor Green

}
```
this function would create the bootable iso natively without oscdimg ^^ another example of powershell usage, there no real reasons to stay on batch, when half your work will invoke powershell or others exe to do the work when powershell can do itself ^^
powershell also include dism commands with error handling and objects usage so instead of dism /mount it would be Mount-WindowsImage but thats all, it would allow you to play with dism in an object oriented way ^^

but that is just my opinion haha ^^

**Comment by rhinotastic** [comment]
It sounds like you just like using powershell so want everything to be in powershell.
Batch has been used for this kind of thing for more than 30 years. It's still used for this heavily at enterprise level. We do a lot of very custom builds and it's all pretty much standard methods using microsoft tools with some 3rd party or inhouse tools.
That whole powershell script above to replace 1 line in batch that uses a standard microsoft tool for this exact job...
Part of the problem with rolling your own methods is when the next person comes along and is expecting the standard approach and finds all this custom methods instead of use of standard tools and there's some bugs to figure out it's a mess, particularly when the project grows.

Can still use powershell but i would really steer clear of breaking from no standard methods of doing things. There's tools that exists and are supported and provided for free by microsoft for this very purpose, use them.

**Comment by panreyes** [comment]
Both solutions are ok. To be honest, powershell would be better, but C# would be the best.

I will give a point to the powershell solution to not requiring oscdimg.exe, as distributing that exe file might be problematic license-wise.

**Comment by ianis58** [comment]
Hi everyone,
For information I have an open pull request #15 that translate that bat script to a PowerShell script.
I also developed a small tool to get the latest windows 11 iso from Microsoft, which you can find linked in the readme.md that is edited in the pull request.
I tried to improve some things to make it more readable, more easy to maintain, and move a small part of the configuration to an external json file.

**Comment by imacks** [comment]
I wrote a similar tool years ago that uses ps under the hood (https://github.com/buildcenter/WindowsBuilder). I've since been mostly on Linux and the project probably needs more love. I reckon it still works on win11 with minor changes.
