### ISSUE TITLE
Acknowledge

### ISSUE THREAD

**Issue by nurmohammed840** [ntdevlabs/tiny11builder#12]
At first, I appreciate your work 👏

But removing application from image does make any difference ?
I mean, There is some debloat scripts, for removing bloated applications...

[Here is some popular debloat scripts](https://github.com/topics/windows-11-debloat), just in case anyone curious...

**Comment by rhinotastic** [comment]
> At first, I appreciate your work 👏
> 
> But removing application from image does make any difference ? I mean, There is some debloat scripts, for removing bloated applications...
> 
> [Here is some popular debloat scripts](https://github.com/topics/windows-11-debloat), just in case anyone curious...

The difference between this approach is you install debloated rather than install then debloat.
The bat script could be improved with for loops and separating the app list from the script so the script stays the same but the file you use for what version doesn't. you only need 1 bat file then and it's much cleaner and easier to maintain.

**Comment by nurmohammed840** [comment]
Please elaborate: 
> The bat script could be improved with for loops and separating the app list from the script so the script stays the same but the file you use for what version doesn't. you only need 1 bat file then and it's much cleaner and easier to maintain.

**Comment by rhinotastic** [comment]
so for example you can have the package name entries stored in a file for each windows release version. the batch script can then use a for loop to go through each entry in the selected file and then execute the command with that package name to remove.
this means you have a function for looping through a file to remove the packages listed in that file. You only then need to update or add/remove package names to the file rather than have to put in a full command entry to the batch script for each package.
you also don't then have to have multiple batch scripts but can have a single script and make new windows version files for the script to use.
