### ISSUE TITLE
Please add multilanguage support

### ISSUE THREAD

**Issue by Elrondo46** [ntdevlabs/tiny11builder#136]
Can you add this possibility or make a howto about that ?

**Comment by Elrondo46** [comment]
Not true. Downloaded a french edition results generating a US edition

**Comment by Elrondo46** [comment]
`Default system UI language code not found.`

This is the error

**Comment by Wasp5016** [comment]
same for German (de-de)
Cause is dism-cmd in line 58 gives out localized information.
Add parameter /English at the end of this line so the output is english and the regex matches.

**Comment by ntdevlabs** [comment]
This might sound like a cliche, but... it works for me!
I tried making an ISO from the Romanian release of Windows 11 and it worked flawlessly.
<img width="461" alt="Screenshot 2024-04-23 222127" src="https://github.com/ntdevlabs/tiny11builder/assets/38796849/7c4266b5-3d37-409a-ae46-5eb8e68eb62c">
![Windows 11-2024-04-23-22-47-18](https://github.com/ntdevlabs/tiny11builder/assets/38796849/3f46dc26-afad-453d-ac99-36024d5eab9e)
![Windows 11-2024-04-23-22-47-18](https://github.com/ntdevlabs/tiny11builder/assets/38796849/2c95f281-3010-43ce-af51-80ef31701cff)

**Comment by bwRavencl** [comment]
@ntdevlabs For me the image creation also worked - however the app removal step did not work as intended due to this issue.

The problematic line in my case is `if ($_ -match 'PackageName : (.*)') {`, this line works only correctly, if the output of `dism` is in English, but e.g. on my machine it is in German. Consequently the `$packages` variable remains empty, resulting in non of the provisioned apps getting removed.

Please see my PR #140 which incorporates the fix suggested by @Wasp5016 for all calls of `dism`.

**Comment by bai0012** [comment]
For the Chinese version of the mirror, although this error occurred, there is no problem after installation.
