### ISSUE TITLE
My tiny 11 is crashing

### ISSUE THREAD

**Issue by xdxddxd** [ntdevlabs/tiny11builder#37]
I'm using the noreq b2 version, but i'm having constants BSOD.

16gb Ram
AMD FX-6300
RTX 2060

What can i do to fix it ?

**Comment by alexfeed1990** [comment]
Im not too experienced with tiny11, but, the first step in sorting out BSOD's is normally to upload the minidump files and the error code. Since your computer has constant BSOD'ing theres probably no chance that you'll be able to upload the minidumps by normal means, but in this case i suppose you have the install usb that you used to install tiny11. You can probably access the minidumps stored by windows with the install usb and store them on a separate usb to upload on another computer.
