### ISSUE TITLE
if path has space in it, image is not created

### ISSUE THREAD

**Issue by cood1n** [ntdevlabs/tiny11builder#39]
essentially i tried running the tool in my downloads folder and after it finished making the image and was attempting to copy it back to it's folder, it errored that a path called "C:\Users\My" did not exist and then failed, wasting all of time that i spent waiting for it.

my user folder is named "My Name" which leads me to believe the space in my user folder broke it.

also i seem like the only person that can right more than 2 sentences in the issue section of this repo, sorry about that man

**Comment by rshanule** [comment]
I can corroborate this

**Comment by jazzman1825** [comment]
All the similar issues are caused by the problem described in this thread. The letter of the path to the tiny11builder should not matter unless the path does not contain spaces. For everyone else facing the same issue, just extract the archive directly into the drive root directory or make sure there are no spaces in the path to the bat file.
