### ISSUE TITLE
After mounting my ISO, it will not go past the drive letter part.

### ISSUE THREAD

**Issue by MandoCorp420** [ntdevlabs/tiny11builder#52]

**Comment by IAmSentiel** [comment]
Hi Mando,
I had this issue too, found that it was because I was missunderstanding the instructions.

Follow these steps and it should work:

1- Download your windows ISO from microsoft.
2- When it is downloaded, double-click on the windows ISO to open it, and keep the folder open in the background.
**Take note of the Drive letter it is assigned.**
3- Run the Tiny11 builder as administrator.
4- When asked for a Drive letter, enter the Drive letter that the Windows ISO was assigned.

This should solve your issue.

Also worth noting, after this step it will list an index of Windows options, and ask you for an index; for this step enter the number of the windows install you want - This is not the windows version e.g. 7, 10, 11, this is the index number listed against the version you want.

**Comment by gthaka** [comment]
Just a Heads Up. Had the same issue recreated by just putting a collon (:) after the Drive Letter. I had already mounted it to Drive F.

So Idealy, don't put a collon after the letter. In my case just (F)

**Comment by metheowww** [comment]
I had this issue too on windows 10, and fixed it by changing the script a little bit:
From this:
```
if not exist "%DriveLetter%\sources\boot.wim" (
	echo.Can't find Windows OS Installation files in the specified Drive Letter..
	echo.
	echo.Please enter the correct DVD Drive Letter..
	goto :Stop
)

if not exist "%DriveLetter%\sources\install.wim" (
	echo.Can't find Windows OS Installation files in the specified Drive Letter..
	echo.
	echo.Please enter the correct DVD Drive Letter..
	goto :Stop
)
```

To this:
```
if exist "%DriveLetter%\sources\boot.wim" goto next1 else (
	echo Can't find Windows OS Installation files in the specified Drive Letter..
	echo.
	echo Please enter the correct DVD Drive Letter..
	goto :Stop
)
:next1
if exist "%DriveLetter%\sources\install.esd" goto next2 else (
	echo Can't find Windows OS Installation files in the specified Drive Letter..
	echo.
	echo Please enter the correct DVD Drive Letter..
	goto :Stop
)
:next2

```

**Comment by idarkkz** [comment]
Thank you @metheowww 
It's actually one line that needed to be edited:

From:
`
if exist "%DriveLetter%\sources\install.esd" goto next2 else (
`

To:
`
if exist "%DriveLetter%\sources\install.esd" goto next2 else (
`

**Comment by stormsnsnow** [comment]
> I had this issue too on windows 10, and fixed it by changing the script a little bit: From this:
> 
> ```
> if not exist "%DriveLetter%\sources\boot.wim" (
> 	echo.Can't find Windows OS Installation files in the specified Drive Letter..
> 	echo.
> 	echo.Please enter the correct DVD Drive Letter..
> 	goto :Stop
> )
> 
> if not exist "%DriveLetter%\sources\install.wim" (
> 	echo.Can't find Windows OS Installation files in the specified Drive Letter..
> 	echo.
> 	echo.Please enter the correct DVD Drive Letter..
> 	goto :Stop
> )
> ```
> 
> To this:
> 
> ```
> if exist "%DriveLetter%\sources\boot.wim" goto next1 else (
> 	echo Can't find Windows OS Installation files in the specified Drive Letter..
> 	echo.
> 	echo Please enter the correct DVD Drive Letter..
> 	goto :Stop
> )
> :next1
> if exist "%DriveLetter%\sources\install.esd" goto next2 else (
> 	echo Can't find Windows OS Installation files in the specified Drive Letter..
> 	echo.
> 	echo Please enter the correct DVD Drive Letter..
> 	goto :Stop
> )
> :next2
> ```

2 years later and this solution works perfectly. Thanks @metheowww
