### ISSUE TITLE
Tiny 11 Builder Outputs "Pro" Version, but its actually Enterprise Windows Version

### ISSUE THREAD

**Issue by erickbadilla** [ntdevlabs/tiny11builder#54]
Is this an expected way that Tiny 11 Builder should work? Or should it produce the desired Windows 11 version we pick?

Currently tried installing two times on my laptop Windows 11 Pro version, but it always installs Windows Enterprise Edition.

I tried checking the version installed on my bootable USB drive with this command 

`dism /Get-WimInfo /WimFile:F:\sources\install.wim /index:1
`

And it reports Windows 11 Pro version,
but my computer-installed version is Windows 11 Enterprise.

**Comment by Crytek01** [comment]
**Windows 11 Website ISO Version:**

![image](https://user-images.githubusercontent.com/39202274/235487270-8f13e90e-d1c9-497b-af1d-0cda6cf50076.png)

**Windows 11 Tiny Build Output Version:**

![image](https://user-images.githubusercontent.com/39202274/235487029-a39c1446-dec8-41ff-a9f8-0ee13b8af72c.png)

**Windows 11 Installed version:**

![image](https://user-images.githubusercontent.com/39202274/235487765-83ba71d5-b0f1-4c5c-b193-31cbe338908f.png)

**Comment by apersonintech** [comment]
I've seen this happen from time to time, but not in your exact way. It's an issue with Windows and not due to Tiny11's doing. 

The fix I've found that works for me is to apply go to Settings › Activation › Change product key and enter 
Windows 11 Pro (generic key): VK7JG-NPHTM-C97JM-9MPGT-3V66T
or 
Windows 11 Pro N (generic key): 2B87N-8KFHP-DKV6R-Y2C8J-PKCKT

That has always fixed it for me, hopefully it works for you.

**Comment by TripleU-613** [comment]
I'm setting up tiny11 and for some reason, on this specific PC, it asks me for a activation code... Why?
