### ISSUE TITLE
Error: 15601

### ISSUE THREAD

**Issue by IoakeimSogiakas** [ntdevlabs/tiny11builder#64]
I just constantly get Error: 15601. After it finishes it doesnt generate a file (probably due to the error)

**Comment by ger5ones** [comment]
I'm having the exact same issue.

**Comment by ger5ones** [comment]
I was getting the same issue but could generate the tiny11.iso doinig these steps:

1. Make sure to download an Windows.iso file of the versions the author mentioned: 22621.1265 from UUPDump or 22621.525 or 25300. In my case, I had to download from UUPDump (google it and **be aware that it takes a LONG time for it to download/build the .iso**) because the Microsoft .iso is in another version already.

2. If you didn't get the .iso generated, be sure to also download the files **autounattend.xml** (don't know if this one is needed but better copying than finding out later that it was needed - error) and **oscdimg.exe** (if in the final part of the .bat script it occurs some error with this file, you can download/install this tool: https://learn.microsoft.com/en-us/windows-hardware/get-started/adk-install - then copy the C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg\oscdimg.exe (the default install path) to the same directory of the .bat script).

Doing this, you'll get the tiny11.iso generated.

**Though, in my case (building a Home .iso), the error "Windows Setup encountered an internal error while loading or searching for an unattend answer file." appears after I choose "Install now".**

**Comment by IoakeimSogiakas** [comment]
Thank you I will try this
